spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: 'org.h2.Driver'
    username: 'db'
    password: 'password'
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'

org:
  jknetl:
    sleep-metrics:
      test-user:
        username: 'user'
        password: 'password'
        email: 'aa@bb.com'
